package barberadmin1;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author israel
 */
public class LoginPage extends javax.swing.JFrame {

    
    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        LabelNombreApp = new javax.swing.JLabel();
        TxtUsuario = new javax.swing.JTextField();
        LabelUsuario = new javax.swing.JLabel();
        LabelPassword = new javax.swing.JLabel();
        TxtPassword = new javax.swing.JPasswordField();
        jcshow_password = new javax.swing.JCheckBox();
        ButtonLogin = new javax.swing.JButton();
        ButtonExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelNombreApp.setFont(new java.awt.Font("Helvetica Neue", 1, 27)); // NOI18N
        LabelNombreApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNombreApp.setText("BarberShop Manager");
        jPanel1.add(LabelNombreApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 300, 38));
        jPanel1.add(TxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 302, 30));

        LabelUsuario.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        LabelUsuario.setText("Usuario");
        jPanel1.add(LabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 300, 26));

        LabelPassword.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        LabelPassword.setText("Contraseña");
        jPanel1.add(LabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 300, 27));
        jPanel1.add(TxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 302, 30));

        jcshow_password.setText("Mostrar Contraseña");
        jcshow_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcshow_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(jcshow_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 140, 29));

        ButtonLogin.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        ButtonLogin.setText("Login");
        ButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoginActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 115, -1));

        ButtonExit.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        ButtonExit.setText("Exit");
        ButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExitActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 116, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barberadmin1/barbershop-logo-vintage-classic-style-salon-fashion-haircut-pomade-badge-icon-simple-minimalist-modern-barber-pole-razor-shave-scissor-razor-blade-retro-symbol-luxury-elegant-design-free-vector.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoginActionPerformed
        // TODO add your handling code here:
        String myPass=String.valueOf(TxtPassword.getPassword());

        if(TxtUsuario.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Porfavor ingresar usuario");
        }
        else if (myPass.equals("")) {
            JOptionPane.showMessageDialog(null, "Porfavor ingresar Contraseña");
        } else if (validInputs.validCorrectPassword(TxtUsuario.getText(), myPass)){
            //   else if (TxtPassword.getText().equals("Admin") && TxtUsuario.getText().equals("Admin"))        {
            MainPage mainpage = new MainPage();
            mainpage.setVisible(true);
            mainpage.setLocationRelativeTo(null);
            dispose();
        }
        else {
            JOptionPane.showMessageDialog(null, "Username / Password Incorrecta");
        }
        
    }//GEN-LAST:event_ButtonLoginActionPerformed

    private void jcshow_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcshow_passwordActionPerformed
        // TODO add your handling code here:
        if(jcshow_password.isSelected())
            TxtPassword.setEchoChar((char)0);
        else
             TxtPassword.setEchoChar('*');
    }//GEN-LAST:event_jcshow_passwordActionPerformed

    private void ButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ButtonExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonExit;
    private javax.swing.JButton ButtonLogin;
    private javax.swing.JLabel LabelNombreApp;
    private javax.swing.JLabel LabelPassword;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JPasswordField TxtPassword;
    private javax.swing.JTextField TxtUsuario;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jcshow_password;
    // End of variables declaration//GEN-END:variables
}
